/**************************************************************************
* WARNING: 'git_version.h' is automatically generated by make_patchnum.pl
*          DO NOT EDIT DIRECTLY - edit make_patchnum.pl instead
***************************************************************************/
#define PERL_PATCHNUM "v5.37.2-358-g380a1e5"
#define PERL_GIT_UNPUSHED_COMMITS               \
    /*leave-this-comment*/
